yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'
         ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        related_name='posts',
        on_delete=models.SET_NULL
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE,
        verbose_name='Автор', related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст'
    )
    created = models.DateTimeField(
        verbose_name='Дата публикации', auto_now_add=True
    )

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_following',
            )
        ]

yatube/posts/forms.py
from django import forms
from . models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'group': ('Группа'),
            'text': ('Текст'),
        }
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        labels = {
            'text': ('Текст комментария')
        }
        fields = ['text']
        help_texts = {
            'text': 'Напишите комментарий'
        }

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from posts.forms import PostForm, CommentForm
from .models import Group, Post, User, Follow
from django.contrib.auth.decorators import login_required
from .ulits import get_paginated_post
from django.views.decorators.cache import cache_page


@cache_page(20)
def index(request):
    post_list = Post.objects.all()
    page_obj = get_paginated_post(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = get_paginated_post(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = get_paginated_post(request, posts)
    following = (request.user.is_authenticated
                 and author.following.filter(user=request.user).exists())
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'form': form,
        'post': post,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    title = 'Создать новый пост'
    user = request.user
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=user.username)
    context = {
        'title': title,
        'form': form,
        'is_edit': False,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    title = 'Редактировать пост'
    post = get_object_or_404(Post, pk=post_id)
    if request.user.id != post.author_id:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post = form.save()
        post.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'title': title,
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    comment = form.save(commit=False)
    comment.post = post
    comment.author = request.user
    comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    follower_user = request.user
    fol_authors = Follow.objects.filter(user=follower_user).values('author')
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = get_paginated_post(request, posts)
    context = {
        'page_obj': page_obj,
        'fol_authors': fol_authors,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.get(user=request.user, author=author)
    follow.delete()
    return redirect('posts:profile', author)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block header %}{% endblock %}
{% load user_filters %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-10 p-5">
    <div class="card">
        <div class="card-header">{{ header }}</div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                  <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                    <div class="col-md-6">
                    {{ field|addclass:"form-control" }}
                                
                    {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                    {% endif %}
                    </div>                
                </div>
                {% endfor %}
                <div class="col-md-6 offset-md-4">              
                  <button type="submit" class="btn btn-primary">
                  Сохранить
                  </button>
                </div>
            </form>
        </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
Последние обновления у избранных авторов
{% endblock %}
{% block content %}
    {% include 'includes/switcher.html' %}
      <div class="container py-5">     
        <h1>Последние обновления у избранных авторов</h1>
        {% for post in page_obj %}
        <hr>
        <li class="list-group-item">
        {% include 'includes/post_feed_card.html' with display_group_link=True %}
        </li>
        {%endfor%}
      </div>
    {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Записи сообщества: {{ group.title }} - {{ group.description }}
{% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
{% for post in page_obj %}
<li class="list-group-item">
<ul>
  <li>Автор: {{ post.author.get_full_name }}</li>
  <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
</ul>
{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
<img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}
<p>{{ post.text }}</p>
<a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a><br>
</li>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Главная страница {% endblock %}
{% block content %}
<h1>Последние обновления на сайте</h1>
{% include 'includes/switcher.html' %}
{% for post in page_obj %}
<li class="list-group-item">
<ul>
  <li>Автор: {{ post.author.get_full_name }}</li>
  <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
</ul>
{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
<img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}
<p>{{ post.text }}</p>
{% if post.group %}
<a href="{% url 'posts:profile' post.author %}">все посты пользователя</a><br>
<a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a><br>
<a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a><br>
</li>
{% endif %}
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title%} Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content%}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
    <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    {% if post.group %} 
    <li class="list-group-item">
      Группа: {{ post.group }}
      <a href="{% url 'posts:group_list' post.group.slug %}">
      все записи группы
      </a>
    {% endif %}
    </li>
    <li class="list-group-item">
      Автор: {{ post.author.get_full_name }}
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      Всего постов автора:  <span >{{ post.author.posts.count }}</span>
    </li>
    <li class="list-group-item">
      <a href="{% url 'posts:profile' post.author %}">
      все посты пользователя
      {% if user == post.author %}
      <a href="{% url 'posts:edit' post.id %}">
        редактировать пост
      </a><br>
      {% endif %}
      </a>
    </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
    {{ post.text }}
    </p>
  </article>
</div>
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
        <br>
        <h6>Дата публикации: {{ post.pub_date|date:"d-m-Y H:i" }}</h6>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Профайл пользователя {{ author.username }} {% endblock %}
{% block content %}
<div class="mb-5">
  <h1>Все посты пользователя {{ author.get_full_name }}</h1>
  <h3>Всего постов: {{ author.posts.count }}</h3>
  {% if following %}
    <a
      class="btn btn-lg btn-primary"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
    <a
      class="btn btn-lg btn-primary"
      href="{% url 'posts:profile_follow' author.username %}" role="button"
    >
      Подписаться
    </a>
  {% endif %}
</div> 
  {% for post in page_obj %}
  <li class="list-group-item">
  <article>
    <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
      {{ post.text }}
    </p>
    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a><br>
  </article> 
  {% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  </li>
  {% endif %}
{% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
</div>
{% include 'includes/paginator.html' %}
{% endblock %}